@startuml
namespace main {
    class concreteFactory << (S,Aquamarine) >> {
        - name string

        - makeProduct() iAbstractProduct

    }
    class concreteProduct << (S,Aquamarine) >> {
        - attribute string
        - size int

        - setAttribute(attribute string) 
        - getAttribute() string
        - setSize(size int) 
        - getSize() int

    }
    interface iAbstractFactory  {
        - makeProduct() iAbstractProduct

    }
    interface iAbstractProduct  {
        - setAttribute(attribute string) 
        - getAttribute() string
        - setSize(size int) 
        - getSize() int

    }
}

"main.iAbstractFactory" <|-- "main.concreteFactory"
"main.iAbstractProduct" <|-- "main.concreteProduct"

@enduml
