@startuml go-dsgn-pttrn-abstract-factory

namespace abstract-factory {


    class concreteProductA << (S,Aquamarine) >> {
        - behaviourA string
        - featureA int

        + setBehaviour(behaviour string) 
        + getBehaviour() string
        + setFeature(feature int) 
        + getFeature() int

    }

    class concreteProductB << (S,Aquamarine) >> {
        - behaviourB string
        - featureB int

        + setBehaviour(behaviour string) 
        + getBehaviour() string
        + setFeature(feature int) 
        + getFeature() int

    }

    interface iAbstractFactory  {

        + makeProductA() iAbstractProduct
        + makeProductB() iAbstractProduct

    }

    interface iAbstractProduct  {

        + setBehaviour(behaviour string) 
        + getBehaviour() string
        + setFeature(feature int) 
        + getFeature() int

    }

    object Factory {

    }

    class client {

        + createFactory() iAbstractFactory
    }


    object ProductA {

    }

    class concreteFactory << (S,Aquamarine) >> {
        + makeProductA() iAbstractProduct
        + makeProductB() iAbstractProduct

    }

    object ProductB {

    }

}

Factory <.. "abstract-factory.client"

'"abstract-factory.client" ..> "ProductA"
Factory ..> "ProductA"
ProductA <.. "abstract-factory.concreteProductA"
ProductA -[hidden]- "abstract-factory.iAbstractProduct"

'"abstract-factory.client" ..> "ProductB"
Factory ..> "ProductB"
ProductB <.. "abstract-factory.concreteProductB"
ProductB -[hidden]- "abstract-factory.iAbstractProduct"

"abstract-factory.client" o--> "abstract-factory.iAbstractFactory"
"abstract-factory.concreteFactory" --> "abstract-factory.iAbstractProduct"

"abstract-factory.iAbstractFactory" <|.. "abstract-factory.concreteFactory"
"abstract-factory.iAbstractProduct" <|.. "abstract-factory.concreteProductA"
"abstract-factory.iAbstractProduct" <|.. "abstract-factory.concreteProductB"

note "distinct products" as N2
"abstract-factory.concreteProductA" <.[dotted]. N2
N2 .[dotted].> "abstract-factory.concreteProductB"

@enduml
